import React, { Suspense, lazy, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { practiceAreas, steps, faqs } from './content';
import WorldBackground, { EffectBoundary } from './WorldBackground';
import SceneMotion from './SceneMotion';
import './law.css';
const Gavel = lazy(() => import('./GoldSculpture'));
const supported = (() => { try { return Boolean(document.createElement('canvas').getContext('webgl2')); } catch { return false; } })();

function GavelStill() {
  return <svg className="gavel-still" viewBox="0 0 520 440" aria-hidden="true"><defs><linearGradient id="metal" x2="1" y2="1"><stop stopColor="#fafafa"/><stop offset=".45" stopColor="#727780"/><stop offset=".7" stopColor="#d7d9dd"/><stop offset="1" stopColor="#35383d"/></linearGradient></defs><ellipse cx="267" cy="369" rx="151" ry="18" fill="#000" opacity=".35"/><path d="M145 337h237v28H145z" fill="#484c53"/><path d="M155 331h217v15H155z" fill="url(#metal)"/><g transform="rotate(-35 265 220)" fill="url(#metal)" stroke="#cdd0d7" strokeWidth="1"><rect x="252" y="162" width="24" height="172" rx="12"/><rect x="184" y="110" width="160" height="75" rx="14"/><rect x="176" y="105" width="23" height="85" rx="7"/><rect x="330" y="105" width="23" height="85" rx="7"/></g></svg>;
}
function App() {
  const [menu,setMenu] = useState(false), [active,setActive] = useState(0), [open,setOpen] = useState(null), [checked,setChecked] = useState([false,false,false]), [quiet,setQuiet] = useState(false);
  const [reduced,setReduced] = useState(()=>matchMedia('(prefers-reduced-motion: reduce)').matches);
  useEffect(()=>{const q=matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setReduced(q.matches);q.addEventListener('change',update);return()=>q.removeEventListener('change',update);},[]);
  const paused=quiet||reduced;
  useEffect(()=>{document.documentElement.dataset.motion=paused?'paused':'active';},[paused]);
  const area=practiceAreas[active];
  return <><WorldBackground paused={paused} supported={supported}/><SceneMotion paused={paused}/><div className="reading-progress"/><a className="skip-link" href="#expertise">Skip to content</a>
    <header className="site-header"><a className="wordmark" href="#top" aria-label="Law Your Way home">LAW <span>YOUR WAY</span><small>A CLEARER WAY FORWARD</small></a><button className="menu-button" aria-expanded={menu} aria-controls="navigation" onClick={()=>setMenu(!menu)}>{menu?'Close':'Menu'}</button><nav id="navigation" className={menu?'open':''} aria-label="Main navigation" onClick={()=>setMenu(false)}><a href="#expertise">Practice areas</a><a href="#method">Our approach</a><a href="#questions">Questions</a><a className="nav-cta" href="#prepare">Start here ↗</a></nav></header>
    <main><section className="exp-hero wrap" id="top"><div className="hero-copy"><p className="eyebrow">YOUR MATTER. YOUR PRIORITIES.</p><h1>Law, with you<br/>at the <em>center.</em></h1><p className="intro">Understand your options. Protect what matters. Take the next step with a clearer view.</p><div className="hero-actions"><a className="button" href="#expertise">Find your practice area <span>↗</span></a><a className="text-link" href="#method">How it works ↓</a></div><p className="hero-note">Business · Family · Disputes · Defense</p></div><div className="hero-art"><div className="sculpture">{supported&&!paused?<EffectBoundary fallback={<GavelStill/>}><Suspense fallback={<GavelStill/>}><Gavel/></Suspense></EffectBoundary>:<GavelStill/>}</div><div className="art-caption"><span>01 / THE BALANCE OF JUSTICE</span><span>CLARITY. BEFORE ACTION.</span></div></div></section>
    <section className="wrap section" id="expertise"><div className="section-heading exp-heading-row"><div><p className="eyebrow">01 / PRACTICE AREAS</p><h2>What brings<br/>you here?</h2></div><p>Start with the area closest to your situation. Legal questions can overlap; your circumstances come first.</p></div><div className="practice-layout"><div className="practice-tabs" role="tablist" aria-label="Practice areas">{practiceAreas.map((p,i)=><button id={`practice-${i}`} key={p.id} role="tab" aria-selected={active===i} aria-controls="practice-panel" tabIndex={active===i?0:-1} onClick={()=>setActive(i)} onKeyDown={e=>{if(['ArrowDown','ArrowRight','ArrowUp','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?3:(active+(['ArrowDown','ArrowRight'].includes(e.key)?1:3))%4;setActive(next);document.getElementById(`practice-${next}`)?.focus();}}}><span>0{i+1}</span>{p.title}<b aria-hidden="true">↗</b></button>)}</div><div className="practice-panel" id="practice-panel" role="tabpanel" aria-labelledby={`practice-${active}`} tabIndex={0}><p className="eyebrow">THE MATTER / {area.id}</p><h3>{area.title}</h3><p className="summary">{area.summary}</p><p>{area.detail}</p><ul className="tags">{area.tags.map(tag=><li key={tag}>{tag}</li>)}</ul><a className="text-link" href="#prepare">Prepare for a conversation ↗</a></div></div></section>
    <section className="wrap section" id="method"><div className="section-heading exp-heading-row"><div><p className="eyebrow">02 / OUR APPROACH</p><h2>Less uncertainty.<br/>More direction.</h2></div><p>A useful process makes the facts, tradeoffs, and next steps easier to understand.</p></div><div className="steps">{steps.map(s=><article key={s.number}><span className="step-number">{s.number}</span><h3>{s.title}</h3><p>{s.text}</p></article>)}</div></section>
    <section className="wrap section prepare" id="prepare"><div><p className="eyebrow">03 / BEFORE YOU BEGIN</p><h2>A little preparation.<br/>A better conversation.</h2><p>Bring the essentials. Keep sensitive documents private until a firm confirms a secure way to share them.</p></div><div className="checklist"><p className="check-status" aria-live="polite">{checked.filter(Boolean).length} of 3 essentials ready</p>{['A brief timeline of events','Relevant documents and deadlines','The questions you want answered'].map((label,i)=><label key={label}><input type="checkbox" checked={checked[i]} onChange={e=>setChecked(values=>values.map((v,j)=>j===i?e.target.checked:v))}/><span>{label}</span></label>)}</div></section>
    <section className="wrap section questions-grid" id="questions"><div><p className="eyebrow">04 / COMMON QUESTIONS</p><h2>Know where<br/>you stand.</h2><p>A few answers before your next step.</p></div><div className="faq-list">{faqs.map((item,i)=><article className="faq" key={item.q}><h3><button id={`question-${i}`} aria-expanded={open===i} aria-controls={`answer-${i}`} onClick={()=>setOpen(open===i?null:i)}><span>{item.q}</span><b aria-hidden="true">{open===i?'−':'+'}</b></button></h3><div id={`answer-${i}`} role="region" aria-labelledby={`question-${i}`} hidden={open!==i}><p>{item.a}</p></div></article>)}</div></section>
    </main><footer className="wrap"><div className="footer-top"><a className="wordmark" href="#top">LAW <span>YOUR WAY</span></a><a className="text-link" href="#top">Back to top ↑</a></div><p>Website concept. Law Your Way is not a verified law firm. This site provides no legal advice and does not create an attorney–client relationship.</p></footer><button className="motion-control" aria-pressed={paused} disabled={reduced} onClick={()=>setQuiet(!quiet)}>{paused?'Motion paused':'Pause motion'} <span aria-hidden="true">{paused?'▷':'Ⅱ'}</span></button></>;
}
createRoot(document.getElementById('root')).render(<App/>);
